baseURL: http://blog.scottlowe.org
disablePathToLower: true
languageCode: en-us
title: Scott's Weblog
params:
  title: "Scott's Weblog"
  tagline: "The weblog of an IT pro specializing in virtualization, networking, open source, and cloud computing"
  description: "Offering technical posts and how-to articles from an IT pro specializing in virtualization, networking, open source, & cloud computing"
  author:
    name: "Scott Lowe"
    github: "lowescott"
    twitter: "scott_lowe"
    linkedin: "scottslowe"
